// <auto-generated />
using System;
using Databsase.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Databsase.API.Migrations
{
    [DbContext(typeof(UnicornContext))]
    partial class UnicornContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Databsase.API.Data.Entities.HornType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("HornTypes");
                });

            modelBuilder.Entity("Databsase.API.Data.Entities.Unicorn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<Guid?>("HornTypeId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("HornTypeId");

                    b.ToTable("Unicorns");
                });

            modelBuilder.Entity("Databsase.API.Data.Entities.Unicorn", b =>
                {
                    b.HasOne("Databsase.API.Data.Entities.HornType", "HornType")
                        .WithMany()
                        .HasForeignKey("HornTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
